# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 665ab2343f9a6aae2be5f487c85b4d05649f5c1508f2708ce5f7069913d1fd9777ea3a4d029390d77f49e2f2b09840b5ac4f4af3b5eea294d76002a56261fe2e

test:
  secret_key_base: 34e72ed7782ae6a23be7b0b26de843f3de53133a7d0e320cab138c9cd1e230d9f1e83ad77e356da09bafbe12e29d7f1861fd0fb0bad46f92874b4eebaa5ea0ca

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
